[build-system]
requires = ["setuptools>=64", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "pep-compass"
version = "0.0.1"
description = "Repository to develop experiments with riemannian geometry applied to variational autoencoders."
authors = [
  { name = "Jurand Prądzyński", email = "j.pradzynski@student.uw.edu.pl" }
]
readme = "README.md"
requires-python = ">=3.11,<4"

dependencies = [
  "wandb",
  "botorch",
  "poli-core",
  "poli-baselines @ git+https://github.com/MachineLearningLifeScience/poli-baselines.git@main",
  "mapchiral",
  "mhfp",
  "scikit-learn>=1.7",
  "loguru>=0.7.3",
  "seqme[aa-descriptors]>=0.5.0",
  "plotly>=7.1.0",
  "nbformat>=5.11.1",
  "numpy>=1.26.4",
  "scipy>=1.14.1",
  "pandas>=2.2.3",
  "matplotlib>=3.9.4",
  "seaborn>=0.13.2",
  "einops>=0.8.2",
  "cachetools>=7.2.1",
  "levenshtein>=0.27.5",
  "logomaker>=0.8.7",
  "pybktree>=1.1",
]

[project.optional-dependencies]
cpu = [
  "torch==2.10.0",
]
cu126 = [
  "torch==2.10.0",
]
cu128 = [
  "torch==2.10.0",
]

[dependency-groups]
dev = [
  "pytest",
]

[tool.uv]
conflicts = [
  [
    { extra = "cpu" },
    { extra = "cu126" },
  ],
  [
    { extra = "cpu" },
    { extra = "cu128" },
  ],
  [
    { extra = "cu126" },
    { extra = "cu128" },
  ],
]

[tool.uv.sources]
torch = [
  { index = "pytorch-cpu", extra = "cpu" },
  { index = "pytorch-cu126", extra = "cu126" },
  { index = "pytorch-cu128", extra = "cu128" },
]

[[tool.uv.index]]
name = "pytorch-cpu"
url = "https://download.pytorch.org/whl/cpu"
explicit = true

[[tool.uv.index]]
name = "pytorch-cu126"
url = "https://download.pytorch.org/whl/cu126"
explicit = true

[[tool.uv.index]]
name = "pytorch-cu128"
url = "https://download.pytorch.org/whl/cu128"
explicit = true

[workspace]
members = ["analysis"]

[tool.setuptools]
include-package-data = true

[tool.setuptools.packages.find]
where = ["src"]
