"""Proteolysis environment shared across optimization components.

This subpackage holds the reusable *environment* for modelling proteolytic
(exo- and endopeptidase) cleavage: loading MEROPS protease specificity panels
and evaluating the per-bond cleavage susceptibility :math:`\\Phi_{cleav}`. It is
deliberately placed under ``components/helpers`` rather than under a specific
filter, because the same physics is consumed by several components (ranked
CLASP scoring, oracles/black boxes, and analysis notebooks).
"""

from pep_compass.optimization.components.helpers.proteolysis.cleavage import (
    DEFAULT_MEROPS_DATASETS,
    MEROPS_AMINO_ACIDS,
    MEROPS_SUBSITE_OFFSETS,
    MEROPS_SUBSITES,
    CleavagePotential,
    ProteasePanel,
    load_protease_panel,
)
from pep_compass.optimization.components.helpers.proteolysis.background import (
    HUMAN_PROTEOME_COMPOSITION,
    amino_acid_background_from_fasta,
    load_amino_acid_background,
    normalize_background,
    uniform_background,
)
from pep_compass.optimization.components.helpers.proteolysis.dynamics import (
    CleavageEvent,
    Fragment,
    ProteaseKinetics,
    TrajectoryStep,
    apply_event,
    first_cut_distribution,
    fragment_events,
    hazard_concentration,
    simulate_trajectory,
    state_at,
)
from pep_compass.optimization.components.helpers.proteolysis.geometry import (
    EC_SUBSUBCLASS_GEOMETRY,
    EventGeometry,
    allowed_cut_positions,
    enumerate_window_scores,
    geometry_from_ec,
    implied_cleavage_bond,
    geometry_from_name,
    masked_score_from_indices,
    restrict_window_indices,
    masked_window_score,
    resolve_geometry,
    subsite_observability_mask,
    window_residue_indices,
)
from pep_compass.optimization.components.helpers.proteolysis.substrates import (
    CleavageSiteSource,
    SubstrateKind,
    SubstrateParse,
    infer_cleavage_bond,
    parse_substrate,
    reporter_window_indices,
    resolvable_subsites,
)
from pep_compass.optimization.components.helpers.proteolysis.independent_sources import (
    GAP_CHARACTERS,
    compare_specificity_matrices,
    log_probability_matrix,
    specificity_counts_from_windows,
    window_from_sequence,
)
from pep_compass.optimization.components.helpers.proteolysis.specificity import (
    MEROPS_SMOOTHING_ALPHA,
    best_merops_dataset,
    bootstrap_specificity_matrices,
    cluster_profiles,
    expected_null_information_content,
    information_content_excess,
    load_panel_metadata,
    merops_code_locations,
    positional_information_content,
    profile_similarity_matrix,
    specificity_log_odds,
)

__all__ = [
    "restrict_window_indices",
    "compare_specificity_matrices",
    "log_probability_matrix",
    "specificity_counts_from_windows",
    "window_from_sequence",
    "GAP_CHARACTERS",
    "DEFAULT_MEROPS_DATASETS",
    "HUMAN_PROTEOME_COMPOSITION",
    "EC_SUBSUBCLASS_GEOMETRY",
    "EventGeometry",
    "MEROPS_AMINO_ACIDS",
    "MEROPS_SMOOTHING_ALPHA",
    "MEROPS_SUBSITE_OFFSETS",
    "MEROPS_SUBSITES",
    "CleavageEvent",
    "CleavagePotential",
    "CleavageSiteSource",
    "Fragment",
    "ProteaseKinetics",
    "TrajectoryStep",
    "ProteasePanel",
    "SubstrateKind",
    "SubstrateParse",
    "allowed_cut_positions",
    "amino_acid_background_from_fasta",
    "apply_event",
    "best_merops_dataset",
    "bootstrap_specificity_matrices",
    "enumerate_window_scores",
    "cluster_profiles",
    "expected_null_information_content",
    "first_cut_distribution",
    "fragment_events",
    "geometry_from_ec",
    "geometry_from_name",
    "infer_cleavage_bond",
    "hazard_concentration",
    "implied_cleavage_bond",
    "information_content_excess",
    "load_amino_acid_background",
    "load_panel_metadata",
    "load_protease_panel",
    "masked_score_from_indices",
    "masked_window_score",
    "merops_code_locations",
    "normalize_background",
    "parse_substrate",
    "positional_information_content",
    "profile_similarity_matrix",
    "reporter_window_indices",
    "resolve_geometry",
    "resolvable_subsites",
    "simulate_trajectory",
    "state_at",
    "specificity_log_odds",
    "subsite_observability_mask",
    "uniform_background",
    "window_residue_indices",
]
